# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

title: "Chris Wynnyk"
auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 1000 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md"] # files to exclude
url: http://www.wynnyk.com
permalink: /:title/
markdown: rdiscount
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
